import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import FuelConsumption from 'App/Models/FuelConsumption'

export default class FuelConsumptionSeeder extends BaseSeeder {
  public async run () {
    await FuelConsumption.createMany([
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        module_id:1
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        module_id:2
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        module_id:3
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        module_id:4
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        module_id:5
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        module_id:6
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        module_id:7
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        module_id:8
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        module_id:9
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        module_id:10
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        module_id:11
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        module_id:12
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        module_id:1
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        module_id:2
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        module_id:3
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        module_id:4
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        module_id:5
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        module_id:6
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        module_id:7
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        module_id:8
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        module_id:9
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        module_id:10
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        module_id:11
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        module_id:12
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        module_id:1
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        module_id:2
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        module_id:3
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        module_id:4
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        module_id:5
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        module_id:6
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        module_id:7
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        module_id:8
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        module_id:9
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        module_id:10
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        module_id:11
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        module_id:12
      }
    ])
  }
}
