import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import FuelConsumption from 'App/Models/FuelConsumption'

export default class FuelConsumptionSeeder extends BaseSeeder {
  public async run () {
    await FuelConsumption.createMany([
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        vehicle_id:1
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        vehicle_id:2
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        vehicle_id:3
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        vehicle_id:4
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        vehicle_id:5
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:1,
        vehicle_id:6
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        vehicle_id:1
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        vehicle_id:2
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        vehicle_id:3
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        vehicle_id:4
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        vehicle_id:5
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:2,
        vehicle_id:6
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        vehicle_id:1
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        vehicle_id:2
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        vehicle_id:3
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        vehicle_id:4
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        vehicle_id:5
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:3,
        vehicle_id:6
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        vehicle_id:1
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        vehicle_id:2
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        vehicle_id:3
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        vehicle_id:4
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        vehicle_id:5
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:4,
        vehicle_id:6
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        vehicle_id:1
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        vehicle_id:2
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        vehicle_id:3
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        vehicle_id:4
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        vehicle_id:5
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:5,
        vehicle_id:6
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        vehicle_id:1
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        vehicle_id:2
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        vehicle_id:3
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        vehicle_id:4
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        vehicle_id:5
      },
      {
        by_day:2,
        by_week:14,
        by_month:56,
        by_year:672,
        current_year_id:6,
        vehicle_id:6
      }
    ])
  }
}
