import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import PassengersCount from 'App/Models/PassengersCount'

export default class PassengerCountSeeder extends BaseSeeder {
  public async run () {
    await PassengersCount.createMany([
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:1,
        current_year_id:1
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:3,
        current_year_id:1
      },
      {
        nb_passengers_by_day:75,
        nb_passengers_by_week:525,
        nb_passengers_by_month:2100,
        nb_passengers_by_year:25200,
        module_id:3,
        current_year_id:1
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:4,
        current_year_id:1
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:5,
        current_year_id:1
      },
      {
        nb_passengers_by_day:75,
        nb_passengers_by_week:525,
        nb_passengers_by_month:2100,
        nb_passengers_by_year:25200,
        module_id:6,
        current_year_id:1
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:7,
        current_year_id:1
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:8,
        current_year_id:1
      },
      {
        nb_passengers_by_day:75,
        nb_passengers_by_week:525,
        nb_passengers_by_month:2100,
        nb_passengers_by_year:25200,
        module_id:9,
        current_year_id:1
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:10,
        current_year_id:2
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:11,
        current_year_id:2
      },
      {
        nb_passengers_by_day:75,
        nb_passengers_by_week:525,
        nb_passengers_by_month:2100,
        nb_passengers_by_year:25200,
        module_id:12,
        current_year_id:2
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:1,
        current_year_id:3
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:2,
        current_year_id:3
      },
      {
        nb_passengers_by_day:75,
        nb_passengers_by_week:525,
        nb_passengers_by_month:2100,
        nb_passengers_by_year:25200,
        module_id:3,
        current_year_id:4
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:4,
        current_year_id:4
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:5,
        current_year_id:4
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:6,
        current_year_id:3
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:7,
        current_year_id:3
      },
      {
        nb_passengers_by_day:75,
        nb_passengers_by_week:525,
        nb_passengers_by_month:2100,
        nb_passengers_by_year:25200,
        module_id:8,
        current_year_id:4
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:9,
        current_year_id:4
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:10,
        current_year_id:4
      },
      {
        nb_passengers_by_day:75,
        nb_passengers_by_week:525,
        nb_passengers_by_month:2100,
        nb_passengers_by_year:25200,
        module_id:11,
        current_year_id:5
      },
      {
        nb_passengers_by_day:75,
        nb_passengers_by_week:525,
        nb_passengers_by_month:2100,
        nb_passengers_by_year:25200,
        module_id:12,
        current_year_id:4
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:1,
        current_year_id:6
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:2,
        current_year_id:6
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:3,
        current_year_id:6
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:4,
        current_year_id:6
      },
      {
        nb_passengers_by_day:75,
        nb_passengers_by_week:525,
        nb_passengers_by_month:2100,
        nb_passengers_by_year:25200,
        module_id:5,
        current_year_id:6
      },
      {
        nb_passengers_by_day:65,
        nb_passengers_by_week:455,
        nb_passengers_by_month:1820,
        nb_passengers_by_year:21840,
        module_id:6,
        current_year_id:6
      },
      {
        nb_passengers_by_day:25,
        nb_passengers_by_week:175,
        nb_passengers_by_month:700,
        nb_passengers_by_year:8400,
        module_id:7,
        current_year_id:6
      },
    ])
  }
}
