import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import RouteTraveled from 'App/Models/RouteTraveled'

export default class RouteTraveledSeeder extends BaseSeeder {
  public async run () {
    await RouteTraveled.createMany([
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:1,
        vehicle_id:1
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:1,
        vehicle_id:2
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:1,
        vehicle_id:3
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:1,
        vehicle_id:4
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:1,
        vehicle_id:5
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:1,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:1,
        vehicle_id:7
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:2,
        vehicle_id:1
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:2,
        vehicle_id:2
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:2,
        vehicle_id:3
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:2,
        vehicle_id:4
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:2,
        vehicle_id:5
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:2,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:2,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:1
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:2
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:3
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:4
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:5
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:4,
        vehicle_id:1
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:4,
        vehicle_id:2
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:4,
        vehicle_id:3
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:4,
        vehicle_id:4
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:4,
        vehicle_id:5
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:4,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:4,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:1
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:2
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:3
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:4
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:5
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:3,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:5,
        vehicle_id:1
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:5,
        vehicle_id:2
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:5,
        vehicle_id:3
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:5,
        vehicle_id:4
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:5,
        vehicle_id:5
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:5,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:5,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:6,
        vehicle_id:1
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:6,
        vehicle_id:2
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:6,
        vehicle_id:3
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:6,
        vehicle_id:4
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:6,
        vehicle_id:5
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:6,
        vehicle_id:6
      },
      {
        km_by_day:56,
        km_by_week:392,
        km_by_month:1568,
        km_by_year:18816,
        current_year_id:6,
        vehicle_id:6
      }
    ])
  }
}
