import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import TravelTicket from 'App/Models/TravelTicket'

export default class TravelTicketSeeder extends BaseSeeder {
  public async run () {
    await TravelTicket.createMany([
      {
        by_day:75,
        by_week:525,
        by_month:2100,
        by_year:25200,
        vehicle_id:1,
        current_year_id:1
      },
      {
        by_day:25,
        by_week:175,
        by_month:700,
        by_year:8400,
        vehicle_id:3,
        current_year_id:1
      },
      {
        by_day:3,
        by_week:21,
        by_month:84,
        by_year:1008,
        vehicle_id:2,
        current_year_id:1
      },
      {
        by_day:75,
        by_week:525,
        by_month:2100,
        by_year:25200,
        vehicle_id:3,
        current_year_id:2
      },
      {
        by_day:25,
        by_week:175,
        by_month:700,
        by_year:8400,
        vehicle_id:4,
        current_year_id:2
      },
      {
        by_day:3,
        by_week:21,
        by_month:84,
        by_year:1008,
        vehicle_id:5,
        current_year_id:2
      },
      {
        by_day:75,
        by_week:525,
        by_month:2100,
        by_year:25200,
        vehicle_id:6,
        current_year_id:3
      },
      {
        by_day:25,
        by_week:175,
        by_month:700,
        by_year:8400,
        vehicle_id:3,
        current_year_id:3
      },
      {
        by_day:3,
        by_week:21,
        by_month:84,
        by_year:1008,
        vehicle_id:2,
        current_year_id:3
      },
      {
        by_day:75,
        by_week:525,
        by_month:2100,
        by_year:25200,
        vehicle_id:1,
        current_year_id:3
      },
      {
        by_day:25,
        by_week:175,
        by_month:700,
        by_year:8400,
        vehicle_id:4,
        current_year_id:3
      },
      {
        by_day:3,
        by_week:21,
        by_month:84,
        by_year:1008,
        vehicle_id:5,
        current_year_id:3
      },
      {
        by_day:25,
        by_week:175,
        by_month:700,
        by_year:8400,
        vehicle_id:4,
        current_year_id:4
      },
      {
        by_day:3,
        by_week:21,
        by_month:84,
        by_year:1008,
        vehicle_id:5,
        current_year_id:4
      },
      {
        by_day:3,
        by_week:21,
        by_month:84,
        by_year:1008,
        vehicle_id:5,
        current_year_id:5
      },
      {
        by_day:75,
        by_week:525,
        by_month:2100,
        by_year:25200,
        vehicle_id:6,
        current_year_id:5
      },
      {
        by_day:25,
        by_week:175,
        by_month:700,
        by_year:8400,
        vehicle_id:3,
        current_year_id:5
      },
      {
        by_day:3,
        by_week:21,
        by_month:84,
        by_year:1008,
        vehicle_id:2,
        current_year_id:5
      },
      {
        by_day:75,
        by_week:525,
        by_month:2100,
        by_year:25200,
        vehicle_id:1,
        current_year_id:5
      },
      {
        by_day:25,
        by_week:175,
        by_month:700,
        by_year:8400,
        vehicle_id:4,
        current_year_id:6
      },
      {
        by_day:3,
        by_week:21,
        by_month:84,
        by_year:1008,
        vehicle_id:5,
        current_year_id:6
      }
    ])
  }
}
